package application.components;

import java.io.FileOutputStream;
import java.io.InputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import domain.Component;
import domain.Machine;

/**
 * Create and save pdf 
 * 
 * @author FIGUEIRAS Jossua
 */
public class PDF {
    private String docName;
    private Machine machine;
    private Font titleFont;
    private Font subTitleFont;
    private Font bodyFont;
    private boolean success;
    /** 
    * @param name the name of the PDF file to be created (without extension) 
    * @param m the Machine object containing all the information to include
    */
    public PDF(String name, Machine m) {        
        this.docName = name;
        this.machine = m;
        this.success = false;

        InputStream fontStream = getClass().getClassLoader().getResourceAsStream("fonts/roboto.ttf");

        Document document = new Document();

        try {
            BaseFont robotoBase = BaseFont.createFont(
                "fonts/roboto.ttf",
                BaseFont.IDENTITY_H,
                BaseFont.EMBEDDED,
                true,
                fontStream.readAllBytes(),
                null
            );
            this.titleFont = new Font(robotoBase, 16);
            this.subTitleFont = new Font(robotoBase, 14);
            this.bodyFont = new Font(robotoBase, 12);

            PdfWriter.getInstance(document, new FileOutputStream("pdf/" + this.docName + ".pdf"));
            document.open();

            Path pathLogo = Paths.get(ClassLoader.getSystemResource("assets/logo.png").toURI());
            Image logo = Image.getInstance(pathLogo.toAbsolutePath().toString());
            logo.scalePercent(18);
            logo.setSpacingAfter(80f);
            document.add(logo);

            Paragraph title = new Paragraph("Technical data sheet of " + this.machine.getHostname(), this.titleFont);
            title.setAlignment(Element.ALIGN_LEFT);
            title.setSpacingBefore(20f);
            title.setSpacingAfter(20f);
            document.add(title);

            Paragraph infosTitle = new Paragraph("Informations : ", this.subTitleFont);
            infosTitle.setSpacingAfter(10f);
            document.add(infosTitle);

            Paragraph type = new Paragraph("Type : " + this.machine.whoami("Unknown type"), this.bodyFont);
            document.add(type);

            Paragraph ip = new Paragraph("ip address : " + this.machine.getIpAddress(), this.bodyFont);
            document.add(ip);

            Paragraph mac = new Paragraph("mac address : " + this.machine.getMacAdress(), this.bodyFont);
            document.add(mac);

            Paragraph system = new Paragraph("System : " + this.machine.getOs(), this.bodyFont);
            document.add(system);

            Paragraph status = new Paragraph("Status : " + this.machine.getStatus(), this.bodyFont);
            document.add(status);

            Paragraph componentTitle = new Paragraph("Components : ", this.subTitleFont);
            componentTitle.setSpacingBefore(10f);
            componentTitle.setSpacingAfter(10f);
            document.add(componentTitle);

            PdfPTable componentTable = new PdfPTable(3);

            String[] headers = {"Brand", "Model", "Type"};
            for (String h : headers) {
                PdfPCell headerCell = new PdfPCell(new Phrase(h));
                headerCell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                componentTable.addCell(headerCell);
            }

            for(Component c : this.machine.getComponents()){
                PdfPCell brandCell = new PdfPCell();
                brandCell.setPhrase(new Phrase(c.getBrand()));
                componentTable.addCell(brandCell);

                PdfPCell modelCell = new PdfPCell();
                modelCell.setPhrase(new Phrase(c.getModel()));
                componentTable.addCell(modelCell);

                PdfPCell typeCell = new PdfPCell();
                typeCell.setPhrase(new Phrase(c.whoami("Unknown type")));
                componentTable.addCell(typeCell);
            }

            document.add(componentTable);

            Paragraph date = new Paragraph("Generated by siliconmap on " + new SimpleDateFormat("MM/dd/yyyy").format(Calendar.getInstance().getTime()), this.bodyFont);
            document.add(date);

            document.close();
            this.success = true;
        } catch (Exception e) {
            System.out.println("\nError: cannot create PDF document \n" + e);
        }
    }
    /**
     * returns whether the PDF was created and saved successfully
     * 
     * @return true if the PDF was created and saved successfully
     */
    public boolean getSuccess(){
        return this.success;
    }
    /** 
     * @return the name of the document
     */
    public String getDocName(){
        return docName;
    }
}